version: "3"
services:
   # linked_data_server:
   #    image: ghcr.io/zazuko/trifid:v4.1.1
   #    ports:
   #       - "8080:8080"
   #    environment:
   #       SPARQL_ENDPOINT_URL: "http://sparql_endpoint:7878/query"
   #       DATASET_BASE_URL: "http://example.org/"

   # sparql_endpoint:
   #    image: ghcr.io/oxigraph/oxigraph:v0.3.22
   #    volumes:
   #       - ./oxigraph/data:/data
   #    ports:
   #       - "7878:7878"

   sparql_endpoint: # http://localhost:7200/repositories/bcitrg
      image: ontotext/graphdb:10.6.1
      ports:
         - "7200:7200"
      volumes:
         - ./graphdb-data:/data
      environment: 
         GDB_JAVA_OPTS: >-
            -Dgraphdb.workbench.cors.enable=true

   # web_server:
   #    image: php:7.2.2-apache
   #    ports:
   #       - "80:80"
   #    volumes:
   #       - ./web:/var/www/html/
   #    links:
   #       - sparql_endpoint





