version: "3"
services:
   linked_data_server:
      image: ghcr.io/zazuko/trifid:v5.0.1
      ports:
         - "80:8080"
      environment:
         SPARQL_ENDPOINT_URL: "http://sparql_endpoint:7878/query?rewrite=true"
         DATASET_BASE_URL: "http://data.ehu.eus/"
   sparql_endpoint:
      image: ghcr.io/oxigraph/oxigraph:v0.3.22
      volumes:
         - ./oxigraph/data:/data
      ports:
         - "7878:7878"





