version: "3"

services:
   trifid: 
      image: ghcr.io/zazuko/trifid
      ports:
         - "8080:8080"
      environment:
         SPARQL_ENDPOINT_URL: "http://172.17.0.1:9999/blazegraph/namespace/bdl/sparql"
         DATASET_BASE_URL: "https://data.ehu.eus/"